export const GET_POST_REQUEST = "GET_POST_REQUEST";
export const CREATE_POST = "CREATE_POST";
export const GET_ALL_POSTS = "GET_ALL_POSTS";
export const UPDATE_POST = "UPDATE_POST";
export const DELETE_POST = "DELETE_POST";
export const GET_USER = "GET_USER";
export const GET_USER_REQUEST= "GET_USER_REQUEST";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST";
export const DELETE_USER_REQUEST = "DELETE_USER_REQUEST";
export const DELETE_USER = "DELETE_USER";
export const GET_SINGLE_POST_REQUEST = "GET_SINGLE_POST_REQUEST";
export const GET_SINGLE_POST = "GET_SINGLE_POST";
export const UPDATE_SINGLE_POST = "UPDATE_SINGLE_POST";
export const DELETE_SINGLE_POST = "DELETE_SINGLE_POST";
export const ADD_LIKE_POST = "ADD_LIKE_POST";


